const SHORT_SIGNAL_SYMBOL = ".";
const LONG_SIGNAL_SYMBOL = "-";
const SIGNAL_SPACE = " / ";
const SHORT_SIGNAL_BEEP_TIME = 100;
const LONG_SIGNAL_BEEP_TIME = 300;
const SIGNAL_SPACE_BEEP_TIME = 100;
const WORD_SPACE_BEEP_TIME = 300;
const LETTER_SPACE_BEEP_TIME = 100;

const MORSE_CODE = [
  { symbol: "A", morseCode: `${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "B", morseCode: `${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "C", morseCode: `${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "D", morseCode: `${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "E", morseCode: `${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "F", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "G", morseCode: `${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "H", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "I", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "J", morseCode: `${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "K", morseCode: `${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "L", morseCode: `${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "M", morseCode: `${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "N", morseCode: `${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "O", morseCode: `${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "P", morseCode: `${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "Q", morseCode: `${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "R", morseCode: `${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "S", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "T", morseCode: `${LONG_SIGNAL_SYMBOL}` },
  { symbol: "U", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "V", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "W", morseCode: `${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "X", morseCode: `${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "Y", morseCode: `${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "Z", morseCode: `${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "1", morseCode: `${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "2", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "3", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "4", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: "5", morseCode: `${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "6", morseCode: `${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "7", morseCode: `${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "8", morseCode: `${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "9", morseCode: `${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${SHORT_SIGNAL_SYMBOL}` },
  { symbol: "0", morseCode: `${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}${LONG_SIGNAL_SYMBOL}` },
  { symbol: " ", morseCode: SIGNAL_SPACE },
];
